### ISSUE TITLE
Hardware Setup

### ISSUE THREAD

**Issue by roshbhatia** [roshbhatia/toggle#8]

**Comment by coleledger** [comment]
Due to a connection timeout on the BeagleBone we have been unable to pull from the remote Git repo to update the toggle directory.  We also plan to document all of the problems we have come across and our solutions for them as well as add some more directions for the setup process.

**Comment by roshbhatia** [comment]
@junichi3 was able to get the beaglebone connected to the wifi, he installed an ssl cert

**Comment by benhg** [comment]
Making some reasonable progress on this. BBB starting up and we managed to start the virtual printer as well, but so far we have not been able to get the touch responsive.

**Comment by coleledger** [comment]
The BBB that was not was not able to flash with umikaze image has been updated with version on the eMMC in the BBB.  The BBB now is able to boot with an umikaze image.

**Comment by benhg** [comment]
This isn't totally "done", per se, but we have enough hardware working to test our builds pretty well.
