### ISSUE TITLE
Setup Travis Agent for Error Checking

### ISSUE THREAD

**Issue by coleledger** [roshbhatia/toggle#9]
Updating uzmakaki build to allow for use of new toggle version. Might not be 100% necessary with use of git on BBB but could facilitate checking for error in set up also not good use time to reflash BBB vs a git pull.

**Comment by coleledger** [comment]
on one of the BBB blacks we are having an issue such that the flashing will not get past the 
setting LEDs to 

After flashing SD card, then holding s2 while powering BBB. the flashing fails every-time.

**Comment by goeland86** [comment]
Have you tried flashing by just inserting the SD and not holding down S2?
The flashing should just happen by default.

**Comment by coleledger** [comment]
yes I did try holding the s2 button when i was orginly trying to resolve the issue. The rogue BBB that would not take the umikaze image has been updated with new version of of the eMMC and is now working with the umikaze image.

**Comment by roshbhatia** [comment]
Team discussed the possibility of a lightweight build tool, might be worth it to instead use travis to check if the output of toggle produces any errors. Would be a little involved as it requires setting up all the dependencies, gonna look at this over break to figure it out.

**Comment by benhg** [comment]
This is probably not going to happen because it would be very involved to set up the BBBs
